"""
code/perception/grounding.py — ground() dispatch (RF-1 split of
code/grounding.py; docs/refactor_plan.md).

Given ego RGB + depth + target (color, shape) + camera intrinsics, produces:
  - egocentric goal (dist, cos θ, sin θ)
  - confidence score  [0, 1]
  - not_visible flag

`ground()` dispatches between the learned GROUND_NET backend
(code/perception/ground_net.py + code/perception/detector/) and the classical
HSV+depth pipeline (code/perception/hsv_pipeline.py), with a graceful
classical fallback when the GROUND_NET checkpoint is unavailable
(docs/nx9_avoid.md).

This module OWNS all of this pipeline's mutable state (docs/refactor_plan.md
invariant 5): the GROUND_NET* env toggles (read once at import) and the
single `GroundNetState` singleton (detector cache, NX-7 track state,
one-shot notice flags, VF-1 heatmap cache, latency log) live here and only
here. The old top-level `code/grounding.py` is a sys.modules alias to this
exact module object, so old-path callers (`code.grounding.ground`,
`code.grounding.GROUND_NET`, `code.grounding.get_ground_net_last_heatmap()`,
monkeypatching `code.grounding.ground = ...`, etc.) observe precisely the
same state this module mutates -- no copying, no drift.

Validation (standalone)
-----------------------
Run against frames generated by gen_dataset.py; compare (dist, bearing) vs
the privileged GT goal from the parquet `goal` column.

API
---
ground(ego_rgb, ego_depth, target_color, target_shape, intrinsics, robot_yaw=None)
    -> GroundingResult(dist, cos_th, sin_th, confidence, not_visible)

validate_grounding(dataset_dir, n_frames=500)
    -> dict with mean_dist_err, mean_bearing_err_deg, detection_rate
"""
from __future__ import annotations

import math
import os
from pathlib import Path

os.environ.setdefault("MUJOCO_GL", "egl")

import cv2
import numpy as np

from code.perception import ground_net as _gn
from code.perception.geometry import (CAM_ROBOT_FORWARD_OFFSET_M, cam_to_egocentric,
                                      get_ego_intrinsics_rendered)
from code.perception.hsv_config import (EROSION_ITER, GROUND_SHAPE, GROUND_SPLIT, HSV_BOUNDS,
                                        IMG_MARGIN_BOTTOM, IMG_MARGIN_LEFT, IMG_MARGIN_RIGHT,
                                        LOCK_M6, MAX_DEPTH_M, MIN_BLOB_AREA, MIN_CONFIDENCE,
                                        MIN_DEPTH_M, MIN_DEPTH_PROXIMITY_M, MIN_DEPTH_WIDEFOV_M,
                                        MIN_VALID_DEPTH_PX, _env_flag)
from code.perception.hsv_pipeline import ground_classical
from code.perception.hsv_shape_score import _score_all_contours
from code.perception.types import GroundingResult

_REPO_ROOT = Path(__file__).resolve().parents[2]

# NX-9 ADOPTION (docs/nx9_avoid.md §5): default ON. With AVOID resolving the
# ep1 obstacle-collision break that blocked NX-6/NX-7/NX-8's adoption attempts,
# demo under GROUND_NET=1 AVOID=1 scores 13/15 (>= the 13/15 adoption bar; the
# two remaining fails are the documented honest ep2/ep4 failures,
# docs/fa1_failures.md), with easy 15/15 and search 14/15 already gated clean
# for this backend by docs/nx6_final.md. Ships with a graceful classical
# fallback when the checkpoint is missing (see ground()'s dispatch below --
# the deploy repo ships no weights). Opt out with GROUND_NET=0.
GROUND_NET = _env_flag("GROUND_NET", default="1")   # ADOPTED default ON (docs/nx9_avoid.md)
# NX-14 ADOPTION (docs/nx14_detector_v2.md): default points to the v2 detector
# (runs/nx6_heatmap_B/model_best.pt), which beats v1 (runs/nx6_heatmap_A) on
# val/test/failcase recall at matched >=0.9 precision, keeps twin separation
# intact, and held all five closed-loop gate lines with zero reproducible
# regressions. v1's checkpoint is left in place, unmodified, for rollback
# (set GROUND_NET_CKPT=runs/nx6_heatmap_A/model_best.pt and GROUND_NET_TAU=0.59
# to revert). Minimal diff: only this default constant + the paired tau below
# changed; v1's own checkpoint files, training code path, and default-args
# behavior of code/train_nx6_heatmap.py are otherwise untouched.
GROUND_NET_CKPT = os.environ.get(
    "GROUND_NET_CKPT", str(_REPO_ROOT / "runs" / "nx6_heatmap_B" / "model_best.pt"))
# v2's own training-selected deploy operating point (docs/nx14_detector_v2.md,
# runs/nx6_heatmap_B/model_best.pt's saved val_metric: tau=0.64, precision=0.903,
# recall=0.785) -- same selection convention v1's tau=0.59 used (the
# checkpoint's own recorded best-epoch val tau, not a separately re-swept one).
GROUND_NET_TAU    = float(os.environ.get("GROUND_NET_TAU", "0.64"))
GROUND_NET_DEVICE = os.environ.get("GROUND_NET_DEVICE", "cuda")

# NX-7 FIX B (docs/nx7_adoption.md): acquire/track hysteresis, opt-in, default
# OFF. tau_acquire stays GROUND_NET_TAU=0.59 (unchanged -- protects precision
# for a FRESH lock); while the immediately-PRIOR cycle's accepted detection
# ("track" state, reset per grounding call sequence -- see
# reset_ground_net_track()) is available, a marginal continuation detection
# down to GROUND_NET_TAU_TRACK is accepted IF it is spatially continuous with
# that track state, gated by the SAME bearing/distance innovation-gate
# constants code/perception/lock_gate.py's M3 uses downstream (imported
# directly, not duplicated) -- approximates "M3's existing gate" without
# threading LockGate state into ground()'s call signature (keeps the
# zero-call-site-change contract every caller relies on). Track state is
# intentionally SEPARATE from LockGate's own incumbent -- this hysteresis
# operates one layer below M1/M3, at the raw-detection-acceptance boundary.
GROUND_NET_HYSTERESIS = _env_flag("GROUND_NET_HYSTERESIS")   # opt-in, default OFF
GROUND_NET_TAU_TRACK  = float(os.environ.get("GROUND_NET_TAU_TRACK", "0.40"))

# The single GROUND_NET backend state singleton for this process (see
# code/perception/ground_net.py's module docstring for why every mutation
# funnels through this one instance).
_STATE = _gn.GroundNetState()


def get_ground_net_last_heatmap() -> dict | None:
    """
    VF-1 pure-read accessor: the last GROUND_NET grounding cycle's cached
    confidence heatmap, keyed to the query it was computed for.

    Render-side only -- never read by any control-flow code path.

    Returns:
        None if GROUND_NET was never invoked (or is off) in this process,
        or the detector failed to load. Otherwise a dict:
          prob:       (H,W) float32 sigmoid confidence map in [0,1], or None
          confidence: float, the model's raw peak confidence this cycle
          accepted:   bool, whether this cycle's detection was accepted (>= tau,
                      or track-hysteresis continuation)
          color/shape: the (target_color, target_shape) query this cache is for
          cam_type:   'grounding' | 'proximity'
    """
    return _gn.get_last_heatmap(_STATE)


def reset_ground_net_track() -> None:
    """Clear NX-7 FIX B's hysteresis track state. Callers should invoke this
    once at the start of every episode (before the first ground() call) --
    same pattern as constructing a fresh code.perception.lock_gate.LockGate()
    per episode. A no-op (cheap) when GROUND_NET_HYSTERESIS is off."""
    _gn.reset_track(_STATE)


def ground_net_latency_stats() -> dict:
    """Diagnostic helper for smoke tests / gate runs to report GROUND_NET
    latency alongside the closed-loop success metrics.

    Returns:
        Summary stats (ms) over every GROUND_NET inference call made so far
        in this process: n, mean_ms, p50_ms, p95_ms, p99_ms, max_ms. Empty
        dict if GROUND_NET was never invoked.
    """
    return _gn.latency_stats(_STATE)


# ---------------------------------------------------------------------------
# Main grounding function
# ---------------------------------------------------------------------------
def ground(
    ego_rgb:      np.ndarray,   # (H,W,3) uint8
    ego_depth:    np.ndarray,   # (H,W) float32, metres
    target_color: str,          # e.g. "red"
    target_shape: str,          # e.g. "ball"
    intrinsics:   dict,         # {fx,fy,cx,cy,width,height[,pitch_deg]}
    *,
    return_mask: bool = False,
) -> GroundingResult:
    """
    Detect target object and compute egocentric goal.

    Args:
        ego_rgb: BGR or RGB uint8 image (H,W,3).
        ego_depth: Depth map in metres (H,W).
        target_color: Colour name (must be in HSV_BOUNDS).
        target_shape: Shape name -- used for blob filter heuristics.
        intrinsics: Camera intrinsics dict.
        return_mask: If True, attach the binary mask to the result.

    Returns:
        GroundingResult with the detected (dist, cos_th, sin_th, confidence,
        not_visible) and, when applicable, diagnostic fields.
    """
    # NX-6 INTEGRATION (default ON since NX-9 adoption, docs/nx9_avoid.md §5):
    # GROUND_NET swaps in the learned heatmap detector in place of the
    # classical pipeline below, dispatched right here so every existing
    # caller (inferencer.py, eval_search.py, fancy_demo.py) gets the
    # alternative backend with zero call-site changes. `return_mask` has no
    # analogue for the learned backend (no HSV mask exists) and is ignored
    # there.
    #
    # NX-9 graceful classical fallback: if the detector checkpoint is missing
    # or fails to load (the deploy repo ships NO weights), fall through to the
    # classical HSV+depth pipeline below instead of returning not_visible
    # forever (the pre-adoption sticky-failure behavior, which was safe for an
    # opt-in flag but would brick a default-ON deploy without weights). The
    # fallback decision is per-process (load failure is sticky in
    # `code.perception.ground_net.load_detector`) and announced once,
    # clearly, at first use.
    if not GROUND_NET and not _STATE.optout_notified:
        # VR-1 friction fix: the explicit opt-out path previously printed
        # nothing, leaving no evidence of which backend produced a result.
        _STATE.optout_notified = True
        print("[grounding] GROUND_NET=0: learned detector disabled by env; "
              "using the classical HSV+depth pipeline.", flush=True)
    if GROUND_NET:
        det = _gn.load_detector(_STATE, GROUND_NET_CKPT, GROUND_NET_DEVICE, GROUND_NET_TAU)
        if det is not None:
            return _gn.infer(_STATE, ego_rgb, ego_depth, target_color, target_shape, intrinsics,
                             tau=GROUND_NET_TAU, hysteresis=GROUND_NET_HYSTERESIS,
                             tau_track=GROUND_NET_TAU_TRACK)
        # else: one-shot warning already printed by load_detector() / the
        # fallback notice below; continue into the classical pipeline.
        if not _STATE.fallback_warned:
            _STATE.fallback_warned = True
            print(f"[grounding] GROUND_NET detector unavailable (checkpoint "
                  f"missing or failed to load: {GROUND_NET_CKPT!r}) -- "
                  "FALLING BACK to the classical HSV+depth grounding pipeline "
                  "for the rest of this process.", flush=True)

    return ground_classical(ego_rgb, ego_depth, target_color, target_shape, intrinsics,
                            return_mask=return_mask)


# ---------------------------------------------------------------------------
# Validation against dataset GT
# ---------------------------------------------------------------------------
def validate_grounding(
    dataset_dir: str,
    n_frames:    int  = 500,
    verbose:     bool = True,
) -> dict:
    """
    Compare grounding output against privileged GT goal from a generated dataset.

    Args:
        dataset_dir: Path produced by gen_dataset.py.
        n_frames: Number of frames to sample for validation.
        verbose: Print per-episode summary.

    Returns:
        dict with keys: mean_dist_err, mean_bearing_err_deg, detection_rate,
        n_eval.

    Raises:
        FileNotFoundError: If no episode parquet files are found under
            `dataset_dir`.
    """
    import glob
    import json

    from code.arena import EGO_FOVY, EGO_H, EGO_W, get_ego_intrinsics

    data_dir  = os.path.join(dataset_dir, "data", "chunk-000")
    meta_dir  = os.path.join(dataset_dir, "meta")
    video_dir = os.path.join(dataset_dir, "videos")

    parquet_files = sorted(glob.glob(os.path.join(data_dir, "episode_*.parquet")))
    if not parquet_files:
        raise FileNotFoundError(f"No parquet files found in {data_dir}")

    # Read tasks
    tasks = {}
    try:
        tasks_path = os.path.join(meta_dir, "tasks.jsonl")
        with open(tasks_path) as f:
            for line in f:
                t = json.loads(line)
                tasks[t["task_index"]] = t["task"]
    except Exception:
        pass

    intr = get_ego_intrinsics(EGO_W, EGO_H, EGO_FOVY)

    dist_errs:    list = []
    bearing_errs: list = []
    n_detected         = 0
    n_total            = 0

    for pf in parquet_files:
        import pandas as pd
        df = pd.read_parquet(pf)
        if df.empty:
            continue

        ep_idx     = int(df["episode_index"].iloc[0])
        task_idx   = int(df["task_index"].iloc[0])
        task_desc  = tasks.get(task_idx, "")

        # Parse colour and shape from instruction
        color, shape = _parse_instruction(task_desc)
        if color is None:
            continue

        # Load ego RGB video
        ego_mp4 = os.path.join(video_dir, f"episode_{ep_idx:06d}_ego.mp4")
        if not os.path.isfile(ego_mp4):
            continue

        # Read frames lazily (one at a time) to avoid MemoryError
        reader = imageio.get_reader(ego_mp4)
        try:
            n_video_frames = reader.count_frames()
        except Exception:
            n_video_frames = len(df)
        reader.close()

        n_ep_frames = min(len(df), n_video_frames)
        n_sample = max(1, n_frames // len(parquet_files))
        n_sample = min(n_sample, n_ep_frames)
        sample_indices = np.linspace(0, n_ep_frames - 1, n_sample, dtype=int)

        reader = imageio.get_reader(ego_mp4)
        for si in sample_indices:
            if si >= len(df) or si >= n_ep_frames:
                continue

            try:
                frame = reader.get_data(int(si))
            except Exception:
                continue

            row      = df.iloc[si]
            gt_goal  = np.array(row["goal"])  # [dist, cosθ, sinθ]
            gt_dist  = float(gt_goal[0])
            gt_bear  = math.atan2(float(gt_goal[2]), float(gt_goal[1]))

            ego_rgb = np.array(frame, dtype=np.uint8)

            # Use a flat synthetic depth map at GT distance (validation mode)
            ego_depth_synth = np.full((EGO_H, EGO_W), gt_dist, dtype=np.float32)

            result = ground(ego_rgb, ego_depth_synth, color, shape, intr)

            n_total += 1
            if not result.not_visible and result.confidence > MIN_CONFIDENCE:
                n_detected += 1
                dist_err   = abs(result.dist - gt_dist)
                pred_bear  = math.atan2(result.sin_th, result.cos_th)
                bear_err   = abs(math.atan2(
                    math.sin(pred_bear - gt_bear),
                    math.cos(pred_bear - gt_bear)
                ))
                dist_errs.append(dist_err)
                bearing_errs.append(math.degrees(bear_err))
        reader.close()

        if n_total >= n_frames:
            break

    detection_rate     = n_detected / max(1, n_total)
    mean_dist_err      = float(np.mean(dist_errs))    if dist_errs    else float("nan")
    mean_bearing_err   = float(np.mean(bearing_errs)) if bearing_errs else float("nan")

    if verbose:
        print(f"\n[grounding validation]")
        print(f"  frames evaluated : {n_total}")
        print(f"  detected         : {n_detected}  ({detection_rate:.2%})")
        print(f"  mean dist err    : {mean_dist_err:.3f} m")
        print(f"  mean bearing err : {mean_bearing_err:.2f} deg")

    return {
        "mean_dist_err":        mean_dist_err,
        "mean_bearing_err_deg": mean_bearing_err,
        "detection_rate":       detection_rate,
        "n_eval":               n_total,
    }


# ---------------------------------------------------------------------------
# Parse colour/shape from instruction string
# ---------------------------------------------------------------------------
def _parse_instruction(instruction: str) -> tuple[str | None, str | None]:
    """Extract the first matching colour and shape from a text instruction.

    Uses whole-word matching to avoid false positives like 'red' matching
    inside 'purple-colored'.

    Args:
        instruction: Free-text instruction string.

    Returns:
        (color, shape) tuple; either element is None if no match was found.
    """
    import re

    from code.arena import COLORS, SHAPES  # noqa: already in path
    text = instruction.lower()
    color = next(
        (c[0] for c in COLORS
         if re.search(r'\b' + c[0] + r'\b', text)),
        None,
    )
    shape = next((s[0] for s in SHAPES if s[0] in text), None)
    return color, shape


# Lazy import for imageio (used only in validate_grounding)
try:
    import imageio.v2 as imageio
except ImportError:
    import imageio


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------
def _smoke_test() -> None:
    """Synthetic red-ball detection smoke test (also runnable as `python
    code/grounding.py` via the old-path CLI shim, or `python -m
    code.perception.grounding`)."""
    from code.arena import EGO_FOVY, EGO_H, EGO_W, get_ego_intrinsics

    print("grounding.py smoke test...")

    # Synthetic test: render a red ball in a blank image and try to detect it
    h, w = EGO_H, EGO_W
    img = np.zeros((h, w, 3), dtype=np.uint8)
    img[:, :] = [30, 30, 30]   # dark background

    # Draw a red circle in upper-right quadrant
    cx_pix, cy_pix = w * 3 // 4, h // 3
    cv2.circle(img, (cx_pix, cy_pix), 35, (220, 40, 40), -1)   # RGB red

    depth = np.full((h, w), 3.0, dtype=np.float32)  # flat at 3m
    intr  = get_ego_intrinsics(w, h, EGO_FOVY)

    r = ground(img, depth, "red", "ball", intr, return_mask=True)
    print(f"  detected={not r.not_visible}  dist={r.dist:.2f}m  "
          f"yaw_err={math.degrees(math.atan2(r.sin_th,r.cos_th)):.1f}°  "
          f"conf={r.confidence:.2f}")

    # Blue cube — should not detect (no blue in image)
    r2 = ground(img, depth, "blue", "cube", intr)
    print(f"  blue (not present) detected={not r2.not_visible}  (expected False)")

    assert not r.not_visible, "Failed to detect red ball in synthetic image"
    assert r2.not_visible,    "False positive for blue cube"

    print("grounding.py smoke PASS")


if __name__ == "__main__":
    import sys
    _smoke_test()
    sys.exit(0)
