"""
grounding.py — Classical grounding module for G1Nav (ADR Architecture A v2.0).

Given ego RGB + depth + target (color, shape) + camera intrinsics, produces:
  - egocentric goal (dist, cos θ, sin θ)
  - confidence score  [0, 1]
  - not_visible flag

Pipeline
--------
1. HSV colour threshold with per-colour bounds → binary mask
2. Shape/blob filter (min area, circularity) → best candidate blob
3. Morphological erosion to remove noisy border pixels
4. Median depth over eroded mask → back-project to 3-D camera-frame point
5. Rotate from camera frame to egocentric robot frame → (dist, yaw_err)

Validation (standalone)
-----------------------
Run against frames generated by gen_dataset.py; compare (dist, bearing) vs
the privileged GT goal from the parquet `goal` column.

API
---
ground(ego_rgb, ego_depth, target_color, target_shape, intrinsics, robot_yaw=None)
    -> GroundingResult(dist, cos_th, sin_th, confidence, not_visible)

validate_grounding(dataset_dir, n_frames=500)
    -> dict with mean_dist_err, mean_bearing_err_deg, detection_rate
"""

import math
import os

os.environ.setdefault("MUJOCO_GL", "egl")

import numpy as np
import cv2
from dataclasses import dataclass, field
from typing import Optional

import sys as _sys, os as _os
_sys.path.insert(0, _os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))
from code.arena import (backproject_pixel, EGO_FOVY, EGO_W, EGO_H, get_ego_intrinsics,
                        GROUNDING_W, GROUNDING_H)

# E6 fix v4: The MuJoCo model's actual rendered FOVY = model.vis.global_.fovy = 45 degrees.
# The arena.EGO_FOVY constant = 90 degrees is incorrect for the rendered image.
# Using the wrong FOVY inflates focal length error by 2x, causing lateral position errors.
# Override here for grounding only (training pipeline is unaffected).
EGO_FOVY_RENDERED = 45.0  # degrees — actual rendered FOVY (model.vis.global_.fovy)

def get_ego_intrinsics_rendered(w=EGO_W, h=EGO_H):
    """Return intrinsics for the ACTUAL rendered image (FOVY=45 deg, not 90)."""
    import math as _math
    fovy_rad = _math.radians(EGO_FOVY_RENDERED)
    fy = (h / 2.0) / _math.tan(fovy_rad / 2.0)
    fovx_rad = 2.0 * _math.atan(_math.tan(fovy_rad / 2.0) * w / h)
    fx = (w / 2.0) / _math.tan(fovx_rad / 2.0)
    return dict(fx=fx, fy=fy, cx=w / 2.0 - 0.5, cy=h / 2.0 - 0.5,
                width=w, height=h, fovy_deg=EGO_FOVY_RENDERED)


# ---------------------------------------------------------------------------
# HSV colour bounds  (H in [0,179], S/V in [0,255], OpenCV convention)
# ---------------------------------------------------------------------------
# Each entry: list of (lower, upper) tuples — some colours need 2 ranges (red wraps).
#
# TUNING NOTE (E6 grounding-fix):
# MuJoCo renders with ambient=0.4 lighting which desaturates colors.  A 0.4-ambient
# scene raises all channels by ~102 (0.4*255), reducing saturation significantly.
# Measured: red (220,40,40) renders as ~(234,126,126) → HSV S≈118.
#           orange (240,140,30) renders as ~(246,186,120) → HSV S≈131.
# Old S thresholds (120 for red, 140 for orange) excluded these.
# Fix: lower S floor to 60 for all colors so ambient-lit simulated objects are detected.
# The H range is kept tight to avoid cross-color confusion.
HSV_BOUNDS: dict[str, list] = {
    "red":    [
        (np.array([0,   60,  60]), np.array([12,  255, 255])),
        (np.array([165, 60,  60]), np.array([179, 255, 255])),
    ],
    "yellow": [(np.array([18,  60,  80]), np.array([40, 255, 255]))],
    "blue":   [(np.array([100,  60,  60]), np.array([135, 255, 255]))],
    "green":  [(np.array([45,   50,  50]), np.array([88,  255, 255]))],
    "orange": [(np.array([10,   60,  80]), np.array([22, 255, 255]))],
    "purple": [(np.array([125,  40,  40]), np.array([160, 255, 255]))],
    "cyan":   [(np.array([85,   60,  50]), np.array([108, 255, 255]))],
}

# ---------------------------------------------------------------------------
# Shape / blob thresholds
# ---------------------------------------------------------------------------
# V2: MIN_BLOB_AREA lowered to 40px to detect 0.48m targets at 9m at 480x360 resolution.
# At 480x360, a 0.48m ball at 9m covers ~422px² → centroid is reliable even with small mask.
# At 320x240 (native), 9m → 187px². At 480x360, 9m → 422px² (well above 40px threshold).
# After morphological open (removes < 5px radius blobs), clean small blobs remain detectable.
MIN_BLOB_AREA    = 40    # pixels — V2: lowered from 60 to handle distant targets at 9m
EROSION_ITER     = 1     # V2: reduced from 2 (distant tiny blobs erode away at iter=2)

# V5: Shape-discrimination weight — how strongly shape features influence blob selection.
# 0.0 = pure area (old behaviour); 1.0 = pure shape score.
# Set to 0.75: shape features strongly influence and will override moderate area differences.
# A 2× area blob with wrong shape (circ=0.79 vs 0.88) will still lose to correct shape.
SHAPE_WEIGHT     = 0.75  # V5: weight of shape-match score relative to area score

# V5: Two-stage shape selection parameters.
# Stage 1: when >1 blob exists, filter out blobs whose shape_score is significantly below
#   the best shape score among all candidates.
# SHAPE_REL_THRESHOLD: discard blobs with shape_score < best_shape_score * ratio.
# Set to 0.75: if the best ball score is 0.65 (real ball), discard anything < 0.49.
#   A same-color cube (ball score ≈ 0.48) will be filtered; the real ball (0.65) survives.
#   With a single blob, no filtering occurs (no best to compare against).
SHAPE_MIN_THRESHOLD = 0.45   # V5: absolute floor (used as fallback)
SHAPE_REL_THRESHOLD = 0.78   # V5: relative threshold — keep if score >= best*ratio
MAX_DEPTH_M      = 12.0  # discard depth readings beyond this (likely sky/wall)
# E6 fix v3: The MuJoCo ego camera is placed ~0.947m FORWARD of the robot origin
# (due to cam.distance=0.001 + lookat 1m ahead setup in arena._set_ego_cam).
# This means the ROBOT BODY is BEHIND the camera and does NOT appear in frame.
# Therefore, the large 50% bottom crop and 12% side margins are unnecessary and
# were actively BLOCKING valid target detections (targets at 1.5-2.5m appear in
# the lower portion of the image).
# New approach: small 5% bottom crop (for noisy edge pixels) + 3% side margins.
#
# P0 GATE FINDING (2026-07-08, docs/cam_p0.md): lowering this floor (tried 0.18m
# and 0.35m) was ALSO proposed as a P0 prerequisite fix, on the theory that 0.60m
# discarded valid near-field depth. Isolated A/B testing (full 3-skill re-eval,
# n=15 seed=999, plus single-episode causal isolation) showed:
#   - The cam.distance/CAM_ROBOT_FORWARD_OFFSET_M fix ALONE (this floor unchanged
#     at 0.60m) already gives easy 93.3%->100%, demo 60.0%->66.7%, search
#     80.0%->80.0% (zero regression) -- because recalibrating the offset from
#     0.947m->0.10m alone collapses the *effective* near-cutoff from ~1.55m to
#     ~0.7m from the robot origin, without touching this constant at all.
#   - Lowering MIN_DEPTH_M further (0.18 or 0.35, combined with the cam.distance
#     fix) added NO measurable improvement on easy/demo (identical results) but
#     caused a real regression on search (80.0%->73.3%, isolated to one episode:
#     the robot got within 0.53m then overshot/circled instead of stopping).
#     Root cause: trusting depth that close, combined with the now-correct
#     (undrifted, closer-to-body) eye position, opens a detection window into
#     the robot's own self-occlusion zone (legs/feet in frame) -- exactly the
#     risk flagged as unresolved future-work in docs/cam_opt1_widefov.md /
#     docs/cam_opt2_multicam.md ("depth-based self-body rejection" needed).
# Verdict: KEEP this constant at its original 0.60m value; the near-field win
# comes entirely from the geometry fix below, not from relaxing this floor.
MIN_DEPTH_M      = 0.60  # discard depth < 0.6m (sensor noise / very close floor)

# CAM-2 (Phase 1): the PROXIMITY camera's whole purpose is detecting targets down to
# ~0.22-0.3m (docs/cam_opt2_multicam.md geometry), so it cannot use the 0.60m floor above
# (that would blind it over its entire useful range). Used only when
# intrinsics['is_proximity'] is set (see ground() below) -- the grounding/ego cameras keep
# MIN_DEPTH_M=0.60 exactly as the P0 gate validated it.
MIN_DEPTH_PROXIMITY_M = 0.15  # just under the geometric d_near~0.22m; a loose safety net
                              # against degenerate near-zero readings, not the primary
                              # defense (see _reject_depth_outliers below for that).

# CAM-1 (Phase 2, toggle, docs/cam_opt1_widefov.md / docs/cam_p2.md): the wide-FOV
# camera's stated near-field goal is ~0.3m (task brief), same rationale as the
# proximity camera above -- used only when intrinsics['is_widefov'] is set (see
# ground() below). cam2's grounding/ego/proximity paths are unaffected (this key is
# never present in their intrinsics dicts).
MIN_DEPTH_WIDEFOV_M = 0.15    # loose safety net; same value as MIN_DEPTH_PROXIMITY_M
MIN_CONFIDENCE   = 0.05  # V2: lowered from 0.10 (distant targets produce small blobs)

# Reduced margins: robot body is NOT in camera frame (camera is 0.947m ahead of robot).
# Small margins only to handle lens distortion at extreme edges.
IMG_MARGIN_LEFT   = 0.03   # fraction of width to ignore on left/right edges
IMG_MARGIN_RIGHT  = 0.03
IMG_MARGIN_BOTTOM = 0.05   # fraction of height to ignore at bottom (noisy edge pixels)

# V2: minimum valid depth pixels (lowered for distant targets where eroded mask is small)
MIN_VALID_DEPTH_PX = 3   # was 5, reduced for 480x360 high-res render of distant blobs


# ---------------------------------------------------------------------------
# Camera-frame to robot-egocentric transform
# ---------------------------------------------------------------------------
# MuJoCo ego camera: x=right, y=down, z=forward (when tilt=0).
# With downward pitch, the forward direction has a z-component in world frame.
# We treat the camera as a pinhole with the optical axis pointing ≈ forward in
# the robot's horizontal plane for the purpose of bearing estimation.

CAM_PITCH_RAD = math.radians(32.0)   # matches arena.CAM_PITCH

# P0 fix (2026-07-08): arena._set_ego_cam's cam.distance was 0.001 with a lookat
# point 1.0m forward, which placed the TRUE rendered eye at
# `origin + (1-distance)*forward_dir` -- i.e. it DRIFTED with pitch. The old
# 0.947m constant below was empirically measured only at pitch=32 deg
# (0.10 + cos(32deg)*0.999 = 0.947) and was WRONG when reused, unchanged, for
# the grounding render's 26 deg pitch (should have been ~0.10+cos(26)=0.999m).
#
# Now that arena._set_ego_cam uses cam.distance=1.0 (see arena.py comment), the
# true eye sits EXACTLY at `origin_head = pelvis_xy + CAM_FWD*heading, pelvis_z+CAM_HEAD_Z`
# for ANY pitch -- the (1-distance) drift term is now exactly zero. So the
# camera-to-robot forward offset collapses to the constant forward mount offset
# CAM_FWD=0.10m, independent of pitch. This was verified empirically (see
# docs/cam_p0.md): rendering known-position targets through both the 26 deg
# grounding camera and the 32 deg ego camera and comparing ground()'s reported
# (dist, bearing) against the analytic ground-truth confirms the same 0.10m
# constant holds for both pitches (previously a single mismatched constant was
# reused across pitches with no such guarantee).
CAM_ROBOT_FORWARD_OFFSET_M = 0.10  # metres camera is forward of robot origin (CAM_FWD)


def cam_to_egocentric(x_cam: float, y_cam: float, z_cam: float,
                      pitch_deg: float = CAM_PITCH_RAD * 180.0 / math.pi,
                      use_corrected_unpitch: bool = False) -> tuple[float, float]:
    """
    Convert camera-frame 3-D point to robot-egocentric (dist, yaw_err).

    Camera frame: x=right, y=down, z=forward (before pitch).
    We un-pitch the z/y axes to get the horizontal-plane projection,
    then add the camera-to-robot forward offset so the returned values
    are relative to the robot's pelvis origin (matching training data convention).

    Parameters
    ----------
    pitch_deg : camera downward tilt in degrees.
                Use 32° for standard ego render, 20° for grounding render (V2).
                The grounding render uses a shallower pitch so distant targets appear
                in frame; cam_to_egocentric must use the same pitch to un-rotate correctly.
    use_corrected_unpitch : CAM-2/Phase-1 finding (docs/cam_p1.md). The forward-distance
                term below (`z_robot = y_cam*sin + z_cam*cos`) has the WRONG SIGN on the
                y_cam term -- verified by a ground-truth distance sweep (known target
                positions vs. reported dist): at the existing shallow pitches (26°/32°)
                the resulting error is small enough that it hides inside the previously
                -documented "MuJoCo z-buffer underestimation" and the P0 gate still
                passed, but at the new PROXIMITY_PITCH=58° camera the SAME bug makes the
                reported distance *decrease* as the true distance *increases* (completely
                unusable). The geometrically-correct term is `z_cam*cos - y_cam*sin`
                (re-derived from the OpenGL look-at camera convention MuJoCo's free
                camera actually uses, and confirmed empirically: distance now increases
                monotonically with true distance and matches ground truth to within the
                object's own near-surface offset). This flag is threaded from
                `intrinsics['is_proximity']` in ground() below so it activates ONLY for
                the new proximity camera -- the existing, gated 26°/32° grounding/ego
                paths are left byte-for-byte unchanged (zero regression risk). Fixing
                this bug for the grounding camera too is flagged as follow-on work, out
                of scope for this Phase-1 (CAM-2) change.
    """
    # Un-pitch: rotate around camera x-axis by +pitch_rad
    #   x_robot = x_cam
    #   y_robot = y_cam * cos(pitch) - z_cam * sin(pitch)  (vertical)
    #   z_robot = y_cam * sin(pitch) + z_cam * cos(pitch)  (forward)  [pre-existing, see note above]
    pitch_rad = math.radians(pitch_deg)
    cp, sp = math.cos(pitch_rad), math.sin(pitch_rad)
    if use_corrected_unpitch:
        z_robot = z_cam * cp - y_cam * sp   # forward (+ = in front) -- CAM-2 corrected sign
    else:
        z_robot = y_cam * sp + z_cam * cp   # forward (+ = in front) -- pre-existing (unchanged)
    x_robot = x_cam                     # camera x (+ = image right)

    # Add camera-to-robot offset: camera is ~0.947m forward of robot origin.
    # Training goal_vec uses robot origin as reference; grounding uses camera position.
    # This correction aligns the grounding output with the training distribution.
    z_robot += CAM_ROBOT_FORWARD_OFFSET_M

    dist    = math.hypot(x_robot, z_robot)
    # E6 fix v4: MuJoCo's free camera has image x+ = world RIGHT from robot perspective,
    # but in the rendered image small-x (left side) = world-left = POSITIVE yaw_err
    # (matching steer.py's egocentric_goal convention where positive yaw_err = CCW = left).
    # The camera's image x-axis is mirrored relative to the robot's lateral axis.
    # Fix: negate x_robot so that image-left → positive yaw_err (turn left toward target).
    # (Verified empirically to hold at 58° pitch too -- lateral/bearing sign is unaffected
    # by the use_corrected_unpitch fix above, only the forward-distance term was wrong.)
    yaw_err = math.atan2(-x_robot, z_robot)  # positive when target is to the LEFT (CCW)
    return dist, yaw_err


# ---------------------------------------------------------------------------
# V5: Shape-discrimination scoring
# ---------------------------------------------------------------------------
def _shape_match_score(cnt: np.ndarray, target_shape: str) -> float:
    """
    Compute a [0, 1] score measuring how well contour `cnt` matches `target_shape`.

    Features used per shape:
      ball/sphere  → high circularity (4π·A/P²)
      cube/box     → high convex solidity + aspect ratio near 1 (square bbox)
      cylinder     → high convex solidity + aspect ratio > 1 (taller than wide)
      cone         → triangular profile: centroid y < bbox center y (tapered top)
                     + low circularity (triangle ≠ circle)

    Returns 0.0 if contour too small to score reliably.
    """
    area = float(cv2.contourArea(cnt))
    if area < 1.0:
        return 0.0

    peri = cv2.arcLength(cnt, True)
    circ = 4.0 * math.pi * area / (peri * peri + 1e-6)  # 1=circle, 0=line

    # Convex hull solidity: area / convex_hull_area (1=convex, <1=concave)
    hull     = cv2.convexHull(cnt)
    hull_area = float(cv2.contourArea(hull))
    solidity = area / max(1.0, hull_area)

    # Bounding box aspect: h/w (>1 means taller than wide)
    bx, by, bw, bh = cv2.boundingRect(cnt)
    aspect_hw = bh / max(1, bw)   # height/width ratio

    # Centroid position relative to bbox (for cone taper detection)
    M = cv2.moments(cnt)
    if M["m00"] > 0:
        cy_cnt = M["m01"] / M["m00"]  # centroid y in image (row, increases downward)
    else:
        cy_cnt = by + bh / 2.0
    bbox_center_y = by + bh / 2.0
    # Cone: wider at base (bottom), narrow at top.
    # In image coords, top = small row, bottom = large row.
    # For a cone the centroid is BELOW the bbox center (more area in the base).
    # centroid_above = cy_cnt < bbox_center_y  → top-heavy (anti-cone)
    # centroid_below = cy_cnt > bbox_center_y  → bottom-heavy (cone-like)
    centroid_frac = (cy_cnt - bbox_center_y) / max(1, bh)  # -0.5..+0.5; +ve = below center

    shape_key = target_shape.lower()

    # Bounding-box fill ratio: area / (bbox_w * bbox_h)
    # Circle: fill≈0.74; Square: fill≈0.97; Cylinder/Rectangle: fill≈0.95; Triangle≈0.47
    bbox_fill = area / max(1.0, bw * bh)

    if shape_key in ("ball", "sphere"):
        # Ball: high circularity AND low bbox_fill (circle doesn't fill its bbox).
        # circ^3 amplifies the gap: circle 0.88→0.68, square 0.79→0.49.
        # bbox_fill: circle≈0.74, square≈0.97 → complement: circle=0.26, square=0.03.
        # Combined score emphasizes both features.
        low_fill_score = max(0.0, 1.0 - bbox_fill) * 3.0  # 0.78 for circle, 0.09 for square; cap at 1
        low_fill_score = min(1.0, low_fill_score)
        score = 0.5 * (circ ** 3) + 0.5 * low_fill_score

    elif shape_key in ("cube", "box"):
        # Cube: high bbox_fill (square fills bbox ~97%) + aspect ≈ 1.
        # Key discriminator: bbox_fill^3 ≈ 0.91 for cube vs 0.40 for ball.
        # The ^3 exponent dramatically amplifies the fill-ratio gap.
        # Cylinder also has high fill but tall aspect (hw>1.5), which is penalized.
        fill_score  = bbox_fill ** 3   # 0.91 for square, 0.40 for circle, 0.86 for rect
        aspect_score = 1.0 - abs(aspect_hw - 1.0) / 2.0  # 1 at aspect=1, 0 at aspect=3
        aspect_score = max(0.0, aspect_score)
        score = 0.65 * fill_score + 0.35 * aspect_score

    elif shape_key in ("cylinder",):
        # Cylinder: convex + taller than wide (aspect_hw > 1 when viewed from side).
        # Solidity should be high (rectangular cross-section = no concavities).
        # Key discriminator vs cube: aspect_hw >> 1 (cylinder ~2-4, cube ~1).
        # We strongly reward aspect > 1.5 (clearly taller than wide).
        # Note: from directly above a cylinder looks circular, but demo scenes are side-on.
        taller_score = min(1.0, max(0.0, (aspect_hw - 1.0) / 2.0))  # 0 at aspect=1, 1 at aspect=3
        score = 0.4 * solidity + 0.6 * taller_score

    elif shape_key in ("cone",):
        # Cone: triangular profile — tapered top, wider base.
        # Centroid below bbox center (centroid_frac > 0, ideally +0.1 to +0.2 for triangle).
        # Circularity low (triangle << 1).
        taper_score = max(0.0, min(1.0, centroid_frac * 5.0 + 0.5))  # 0 if top-heavy, 1 if bottom-heavy
        non_circle  = 1.0 - circ   # high for triangle/square, 0 for perfect circle
        score = 0.5 * taper_score + 0.5 * non_circle

    else:
        # Unknown shape — neutral score
        score = 0.5

    return float(max(0.0, min(1.0, score)))


def _blob_composite_score(cnt: np.ndarray, target_shape: str,
                          shape_weight: float = SHAPE_WEIGHT,
                          max_area: float = 1.0) -> float:
    """
    Composite score combining relative area and shape match.

    score = shape_weight * shape_match + (1-shape_weight) * norm_area

    norm_area = sqrt(area / max_area) in [0,1] — normalised across the candidate set.
    Call _score_all_contours() instead of this directly for proper normalisation.
    """
    area        = float(cv2.contourArea(cnt))
    norm_area   = math.sqrt(area / max(1.0, max_area))   # [0,1]
    shape_score = _shape_match_score(cnt, target_shape)
    return shape_weight * shape_score + (1.0 - shape_weight) * norm_area


def _score_all_contours(contours: list, target_shape: str,
                        shape_weight: float = SHAPE_WEIGHT,
                        shape_min_thresh: float = SHAPE_MIN_THRESHOLD,
                        shape_rel_thresh: float = SHAPE_REL_THRESHOLD) -> list:
    """
    Two-stage shape-discriminating blob selection.

    Stage 1 (multi-blob filtering): when >1 valid candidate exists:
      - Compute shape_score for all candidates.
      - Find best_shape_score (max across all).
      - Keep only candidates with shape_score >= max(shape_min_thresh,
          best_shape_score * shape_rel_thresh).
      - This filters distractors with clearly wrong shape even if they are
        much larger (closer) than the target.
      - Soft fallback: if ALL candidates fail the filter, keep all (return
        composite-score ranking, no hard veto).

    Stage 2: rank survivors by composite score (normalised area + shape match).

    Returns list of (score, cnt) sorted descending by score.
    """
    if not contours:
        return []
    # Filter by min area
    valid = [(float(cv2.contourArea(c)), c) for c in contours
             if float(cv2.contourArea(c)) >= MIN_BLOB_AREA]
    if not valid:
        return []

    # Compute shape scores for all
    shape_scores = [(_shape_match_score(c, target_shape), a, c) for a, c in valid]

    # Stage 1: multi-blob relative-threshold filtering
    if len(shape_scores) > 1:
        best_ss = max(ss for ss, _, _ in shape_scores)
        # Dynamic threshold: keep if within rel_thresh of the best candidate's shape
        cutoff  = max(shape_min_thresh, best_ss * shape_rel_thresh)
        filtered = [(ss, a, c) for ss, a, c in shape_scores if ss >= cutoff]
        if filtered:
            shape_scores = filtered
        # else: all below cutoff → keep all (soft fallback)

    # Stage 2: composite score with normalised area
    max_a = max(a for _, a, _ in shape_scores)
    scored = []
    for ss, area, cnt in shape_scores:
        norm_a = math.sqrt(area / max(1.0, max_a))
        comp = shape_weight * ss + (1.0 - shape_weight) * norm_a
        scored.append((comp, cnt))
    scored.sort(key=lambda x: x[0], reverse=True)
    return scored


# ---------------------------------------------------------------------------
# CAM-2 (Phase 1): depth-based self-body / near-field-artifact rejection.
# ---------------------------------------------------------------------------
# Concrete failure mode this addresses (empirically confirmed, docs/cam_p1.md): at the
# PROXIMITY camera's steep 58° pitch, once the robot is within ~0.5-0.7m of the target,
# the robot's OWN arms/hands enter the frame flanking the target (visually confirmed by
# rendering a real close-approach walk). Because the robot body is grey/low-saturation
# (g1_gear_wbc.xml rgba 0.2/0.7), it does not itself match the saturated HSV target
# palette -- but color-bleed at object silhouette edges (antialiasing blending the
# target's color with whatever is directly behind/around it, including a nearer
# occluder) can pull a MINORITY of contaminating depth samples into the target's color
# mask, well outside the plausible depth range for a single compact object. This is
# exactly the "self-occlusion" risk flagged as unresolved in docs/cam_opt1_widefov.md /
# docs/cam_opt2_multicam.md and pinned down as the P0 ep14 overshoot mechanism
# (docs/cam_p0.md): trusting depth that close, without this rejection, corrupts the
# median-depth estimate and produces jittery (dist,bearing) that can make the frozen
# policy overshoot/circle instead of stopping.
#
# Mechanism: cluster the valid depth samples into a 1-D histogram (fine bins) and keep
# only the samples in the single largest CONTIGUOUS-nonzero cluster around the modal
# bin. A real object's own surface (even a tall cone/cylinder up to ~0.7m) produces a
# continuous run of depths with no internal gaps, so it always survives as one cluster;
# a disjoint contaminating population (a hand/arm at a very different depth, or floor
# bleeding in through an anti-aliased edge) shows up as a separate cluster across an
# empty gap and gets dropped. This is a much more targeted defense than a blanket depth
# floor (which would either blind the camera over its whole useful near-field range, or
# fail to catch contamination sitting inside the "trusted" range).
DEPTH_CLUSTER_BIN_M = 0.05   # histogram bin width for the contiguous-cluster search


def _reject_depth_outliers(depth_vals: np.ndarray,
                           bin_m: float = DEPTH_CLUSTER_BIN_M) -> np.ndarray:
    """
    Return the subset of depth_vals belonging to the single largest contiguous
    histogram cluster (the modal object surface), discarding a disjoint minority
    population (self-body / edge-bleed contamination -- see module comment above).

    No-op (returns depth_vals unchanged) when there are too few samples to cluster
    meaningfully, or when all samples already sit within one bin.
    """
    if depth_vals.size < 4:
        return depth_vals
    lo, hi = float(depth_vals.min()), float(depth_vals.max())
    if hi - lo < bin_m:
        return depth_vals
    nbins = max(1, int(math.ceil((hi - lo) / bin_m)))
    hist, edges = np.histogram(depth_vals, bins=nbins, range=(lo, hi))
    peak = int(np.argmax(hist))
    lo_bin, hi_bin = peak, peak
    while lo_bin > 0 and hist[lo_bin - 1] > 0:
        lo_bin -= 1
    while hi_bin < len(hist) - 1 and hist[hi_bin + 1] > 0:
        hi_bin += 1
    lo_val, hi_val = float(edges[lo_bin]), float(edges[hi_bin + 1])
    cluster = depth_vals[(depth_vals >= lo_val) & (depth_vals <= hi_val)]
    return cluster if cluster.size > 0 else depth_vals


# ---------------------------------------------------------------------------
# Result dataclass
# ---------------------------------------------------------------------------
@dataclass
class GroundingResult:
    dist:        float         # metres to target (0 if not visible)
    cos_th:      float         # cos(yaw_err)
    sin_th:      float         # sin(yaw_err)
    confidence:  float         # [0, 1]
    not_visible: bool          # True when target not detected
    mask:        Optional[np.ndarray] = field(default=None, repr=False)
    bbox:        Optional[tuple]      = field(default=None, repr=False)  # (x,y,w,h)

    @property
    def goal_vec(self) -> np.ndarray:
        return np.array([self.dist, self.cos_th, self.sin_th], dtype=np.float32)


# ---------------------------------------------------------------------------
# Main grounding function
# ---------------------------------------------------------------------------
def ground(
    ego_rgb:      np.ndarray,   # (H,W,3) uint8
    ego_depth:    np.ndarray,   # (H,W) float32, metres
    target_color: str,          # e.g. "red"
    target_shape: str,          # e.g. "ball"
    intrinsics:   dict,         # {fx,fy,cx,cy,width,height[,pitch_deg]}
    *,
    return_mask: bool = False,
) -> GroundingResult:
    """
    Detect target object and compute egocentric goal.

    Parameters
    ----------
    ego_rgb      : BGR or RGB uint8 image (H,W,3)
    ego_depth    : depth map in metres (H,W)
    target_color : colour name (must be in HSV_BOUNDS)
    target_shape : shape name — used for blob filter heuristics
    intrinsics   : camera intrinsics dict
    return_mask  : if True, attach the binary mask to the result

    Returns
    -------
    GroundingResult
    """
    color_key = target_color.lower().strip()
    if color_key not in HSV_BOUNDS:
        return GroundingResult(0, 1, 0, 0.0, True)

    # CAM-2 (Phase 1): the proximity camera needs its own (lower) depth floor and its
    # own corrected un-pitch sign, and its detections get depth-outlier/self-body
    # clustering. Flag threaded through by ArenaRenderer.render_proximity()'s
    # intrinsics dict -- absent (False) for the existing grounding/ego cameras, so
    # their behaviour is completely unchanged.
    is_proximity   = bool(intrinsics.get('is_proximity', False))
    # CAM-1 (Phase 2, toggle): the wide-FOV camera gets the same near-field treatment
    # (lower depth floor + self-body depth-outlier rejection + corrected un-pitch sign)
    # as the proximity camera, for the same reason -- see ArenaRenderer.render_widefov().
    # Absent (False) whenever cam2's cameras are used, so their behaviour is unchanged.
    is_widefov     = bool(intrinsics.get('is_widefov', False))
    if is_proximity:
        min_depth_eff = MIN_DEPTH_PROXIMITY_M
    elif is_widefov:
        min_depth_eff = MIN_DEPTH_WIDEFOV_M
    else:
        min_depth_eff = MIN_DEPTH_M

    # ---- Colour segmentation ----
    # Convert to HSV (OpenCV expects BGR input)
    if ego_rgb.shape[2] == 3:
        bgr = cv2.cvtColor(ego_rgb, cv2.COLOR_RGB2BGR)
    else:
        bgr = ego_rgb
    hsv = cv2.cvtColor(bgr, cv2.COLOR_BGR2HSV)

    mask = np.zeros(hsv.shape[:2], dtype=np.uint8)
    for lo, hi in HSV_BOUNDS[color_key]:
        mask |= cv2.inRange(hsv, lo, hi)

    # ---- E6 fix: mask out robot-body self-occlusion region ----
    # The ego camera sees the robot's arms/torso in the lower portion and side edges.
    # Zero out those image regions to prevent false self-detections.
    h_img, w_img = mask.shape[:2]
    l_px = int(IMG_MARGIN_LEFT   * w_img)
    r_px = int(IMG_MARGIN_RIGHT  * w_img)
    b_px = int(IMG_MARGIN_BOTTOM * h_img)
    if l_px > 0:
        mask[:, :l_px] = 0
    if r_px > 0:
        mask[:, w_img - r_px:] = 0
    if b_px > 0:
        mask[h_img - b_px:, :] = 0

    # ---- Shape / blob filter ----
    # V2: use smaller kernel at higher resolutions to avoid erasing tiny distant blobs.
    # At 480x360, a 5x5 kernel covers the same angular area as a ~3x3 at 320x240.
    # Scale kernel with image area relative to native 320x240.
    _scale = math.sqrt((h_img * w_img) / (240.0 * 320.0))
    _k = max(3, int(round(5 * _scale)) | 1)  # ensure odd; min 3
    kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (_k, _k))
    mask   = cv2.morphologyEx(mask, cv2.MORPH_OPEN,  kernel, iterations=1)
    mask   = cv2.morphologyEx(mask, cv2.MORPH_CLOSE, kernel, iterations=1)

    contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    if not contours:
        return GroundingResult(0, 1, 0, 0.0, True,
                               mask=(mask if return_mask else None))

    # ---- Select best blob (V5: shape-discriminating composite score) ----
    # When multiple same-color blobs exist (distractors), we pick the one whose
    # contour geometry best matches the instructed shape (ball/cube/cylinder/cone).
    # We normalise area across all candidates so a 2-3× larger distractor cannot
    # overwhelm the shape signal (SHAPE_WEIGHT=0.75 gives shape the majority vote).
    scored_contours = _score_all_contours(contours, target_shape, shape_weight=SHAPE_WEIGHT)

    if not scored_contours:
        return GroundingResult(0, 1, 0, 0.0, True,
                               mask=(mask if return_mask else None))

    best_score, best_cnt = scored_contours[0]
    best_area = float(cv2.contourArea(best_cnt))

    if best_cnt is None or best_area < MIN_BLOB_AREA:
        return GroundingResult(0, 1, 0, 0.0, True,
                               mask=(mask if return_mask else None))

    # ---- Blob mask and bbox ----
    blob_mask = np.zeros_like(mask)
    cv2.drawContours(blob_mask, [best_cnt], -1, 255, cv2.FILLED)

    x, y, w, h = cv2.boundingRect(best_cnt)
    cx_px = x + w / 2.0
    cy_px = y + h / 2.0

    # ---- Erode mask before depth sampling ----
    erode_k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
    eroded  = cv2.erode(blob_mask, erode_k, iterations=EROSION_ITER)

    # ---- Depth estimation ----
    depth_vals = ego_depth[eroded > 0]
    valid      = depth_vals[(depth_vals > min_depth_eff) & (depth_vals < MAX_DEPTH_M)]
    if is_proximity or is_widefov:
        # CAM-2/CAM-1 self-body / near-field-artifact rejection (see module comment
        # above _reject_depth_outliers): drop a disjoint contaminating depth population
        # (robot's own arm/hand, or an anti-aliased edge-bleed pixel) before the
        # median is computed, rather than hoping the median alone is robust to it.
        valid = _reject_depth_outliers(valid)

    if len(valid) < MIN_VALID_DEPTH_PX:
        # E6 fix: if depth is insufficient (all pixels within robot-body range or
        # too sparse), treat as NOT visible — a spurious color blob at robot-body
        # depth should not be used as a goal direction.
        # V2: lowered from 5 to MIN_VALID_DEPTH_PX=3 for distant tiny blobs.
        return GroundingResult(0, 1, 0, 0.0, True,
                               mask=(blob_mask if return_mask else None),
                               bbox=None)

    # ---- Foreground cluster filter ----
    # E6 fix v3: detect and reject background wall false positives.
    # A blob that is very large (>30% of valid image area) AND spans a wide depth
    # range (>0.8m) is likely the arena wall/floor being mistakenly detected, not
    # the actual target object. Real objects are compact and at a consistent depth.
    valid_image_area = (h_img - int(IMG_MARGIN_BOTTOM * h_img)) * (w_img - int((IMG_MARGIN_LEFT + IMG_MARGIN_RIGHT) * w_img))
    blob_fill_ratio = best_area / max(1, valid_image_area)
    depth_range = float(np.percentile(valid, 90)) - float(np.percentile(valid, 10))

    # Check if blob is a foreground object (compact & consistent depth) or background
    is_background_blob = (blob_fill_ratio > 0.30 and depth_range > 0.7)
    if is_background_blob:
        # V3 DEPTH-FG RESCUE: when the whole image is cyan/blue-tinted (e.g. arena
        # walls render at H≈104-105 which overlaps cyan/blue HSV bounds), the HSV
        # mask covers 80%+ of the frame and gets correctly rejected by the background
        # filter above.  But the ACTUAL object is still present — it's just a compact
        # foreground cluster sitting in front of the cyan-tinted background.
        #
        # Fix: re-run blob detection using ONLY pixels that are significantly CLOSER
        # than their local neighbourhood (depth-gradient foreground mask).  This
        # separates the target object (at its true depth) from the arena surfaces
        # (at the peripheral depth).  We use a uniform filter as a fast local-mean
        # estimate (scipy not required — we use cv2.blur for speed).
        #
        # Threshold: pixel is foreground if depth < local_mean - FG_DEPTH_MARGIN.
        # FG_DEPTH_MARGIN=0.15m: objects 15 cm closer than background are selected.
        # This safely handles targets at 4-9m against walls at 5-11m.
        FG_DEPTH_MARGIN = 0.15   # metres — foreground/background separation
        FG_BLUR_K = 51           # pixels — neighbourhood size for local mean (must be odd)
        depth_f = ego_depth.copy()
        depth_f[depth_f > MAX_DEPTH_M] = MAX_DEPTH_M  # cap far values
        local_mean = cv2.blur(depth_f, (FG_BLUR_K, FG_BLUR_K))
        fg_depth_mask = (ego_depth < local_mean - FG_DEPTH_MARGIN)

        # Intersect HSV mask (pre-morphology) with foreground depth mask
        # Rebuild the raw HSV mask (before morphology) intersected with depth-fg
        raw_hsv = np.zeros(hsv.shape[:2], dtype=np.uint8)
        for lo_b, hi_b in HSV_BOUNDS[color_key]:
            raw_hsv |= cv2.inRange(hsv, lo_b, hi_b)
        # Apply margins
        if l_px > 0: raw_hsv[:, :l_px] = 0
        if r_px > 0: raw_hsv[:, w_img - r_px:] = 0
        if b_px > 0: raw_hsv[h_img - b_px:, :] = 0

        fg_mask_u8 = (fg_depth_mask & (raw_hsv > 0)).astype(np.uint8) * 255

        # Morphological cleanup on the FG mask
        fg_mask_u8 = cv2.morphologyEx(fg_mask_u8, cv2.MORPH_OPEN,  kernel, iterations=1)
        fg_mask_u8 = cv2.morphologyEx(fg_mask_u8, cv2.MORPH_CLOSE, kernel, iterations=1)

        fg_contours, _ = cv2.findContours(fg_mask_u8, cv2.RETR_EXTERNAL,
                                          cv2.CHAIN_APPROX_SIMPLE)
        # Pre-filter: reject wall-stripe artifacts (wide+shallow → aspect > 8.0).
        valid_fg = []
        for cnt in fg_contours:
            a = float(cv2.contourArea(cnt))
            if a < MIN_BLOB_AREA:
                continue
            _bx, _by, _bw, _bh = cv2.boundingRect(cnt)
            if _bw / max(1, _bh) > 8.0:
                continue
            valid_fg.append(cnt)
        # V5 NOTE: FG rescue uses AREA-ONLY selection (no shape discrimination).
        # Reason: in FG rescue scenarios (cyan/blue wall overlap), the target may be
        # MUCH farther than the distractor. Filtering distractors by shape in FG rescue
        # often causes the ONLY detected FG blob to be discarded (the close distractor
        # is filtered but the far target is not in the FG mask at all), resulting in
        # not_visible and robot drift. The primary path (above) handles shape discrimination
        # for non-wall-overlap multi-blob cases. FG rescue falls back to largest-area
        # (V4 behavior) to maximize detection reliability.
        fg_best_cnt  = None
        fg_best_area = 0.0
        fg_best_score = 0.0
        for cnt in valid_fg:
            a = float(cv2.contourArea(cnt))
            if a > fg_best_score:
                fg_best_score = a
                fg_best_area = a
                fg_best_cnt = cnt

        if fg_best_cnt is None:
            # Depth-FG rescue also failed — truly not visible
            return GroundingResult(0, 1, 0, 0.0, True,
                                   mask=(blob_mask if return_mask else None),
                                   bbox=None)

        # Use the depth-FG blob as the detection
        blob_mask = np.zeros_like(mask)
        cv2.drawContours(blob_mask, [fg_best_cnt], -1, 255, cv2.FILLED)
        x, y, w, h = cv2.boundingRect(fg_best_cnt)
        cx_px    = x + w / 2.0
        cy_px    = y + h / 2.0
        best_area = fg_best_area

        erode_k = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (3, 3))
        eroded  = cv2.erode(blob_mask, erode_k, iterations=EROSION_ITER)
        depth_vals = ego_depth[eroded > 0]
        valid      = depth_vals[(depth_vals > min_depth_eff) & (depth_vals < MAX_DEPTH_M)]
        if is_proximity or is_widefov:
            valid = _reject_depth_outliers(valid)

        if len(valid) < MIN_VALID_DEPTH_PX:
            return GroundingResult(0, 1, 0, 0.0, True,
                                   mask=(blob_mask if return_mask else None),
                                   bbox=None)

        # FG rescue background check: the wall-edge artifact appears as a wide, shallow
        # stripe (large width, small height → large aspect ratio).
        # Real target objects are compact: balls ≈ circular, cubes ≈ square, cones/cylinders
        # are tall. Maximum expected aspect ratio for a real object: ~3-4.
        # Wall-edge artifacts: width >> height (aspect ratio 10-30).
        # Also apply the fill-ratio AND depth-range filter from the main loop.
        fg_fill_ratio  = fg_best_area / max(1, valid_image_area)
        fg_depth_range = (float(np.percentile(valid, 90)) - float(np.percentile(valid, 10))
                          if len(valid) > 10 else 0.0)
        # Aspect ratio: w = bbox width, h = bbox height (from cv2.boundingRect(fg_best_cnt))
        # Note: 'w' and 'h' were set by the cv2.boundingRect(fg_best_cnt) call above.
        fg_bbox_aspect = w / max(1, h)   # width / height of FG blob bounding box
        # Reject if: fill-ratio+depth-range fail OR blob is extremely wide+shallow (wall stripe)
        fg_is_background = ((fg_fill_ratio > 0.30 and fg_depth_range > 0.7) or
                            fg_bbox_aspect > 8.0)
        if fg_is_background:
            return GroundingResult(0, 1, 0, 0.0, True,
                                   mask=(blob_mask if return_mask else None),
                                   bbox=None)

    depth_m = float(np.median(valid))

    # ---- Back-project centroid to 3-D ----
    pt3d    = backproject_pixel(cx_px, cy_px, depth_m, intrinsics)
    # V2: if intrinsics contains 'pitch_deg' (from grounding render), use it.
    # The grounding render uses GROUNDING_PITCH=20° (not 32°), so cam_to_egocentric
    # must un-rotate with the same pitch to get correct bearing and distance.
    pitch_deg_for_unrot = float(intrinsics.get('pitch_deg', CAM_PITCH_RAD * 180.0 / math.pi))
    # CAM-1 (Phase 2, toggle): the widefov camera's pitch (WIDEFOV_PITCH=42 deg) is
    # steep enough that the pre-existing un-pitch sign bug (docs/cam_p1.md) is a real
    # risk (it was fatal at PROXIMITY_PITCH=58 deg, small-but-present at 26/32 deg) --
    # empirically verified monotonic/accurate via a distance-sweep bench before this
    # was locked in (see docs/cam_p2.md, bench_widefov_dist.py).
    dist, yaw_err = cam_to_egocentric(pt3d[0], pt3d[1], pt3d[2], pitch_deg=pitch_deg_for_unrot,
                                      use_corrected_unpitch=(is_proximity or is_widefov))

    dist = max(0.0, dist)

    # ---- Confidence ----
    max_area     = float(ego_rgb.shape[0] * ego_rgb.shape[1])
    conf_area    = min(1.0, best_area / (max_area * 0.5))   # saturates at 50% fill
    conf_depth   = 1.0 if len(valid) > 20 else len(valid) / 20.0
    confidence   = float(0.6 * conf_area + 0.4 * conf_depth)
    confidence   = min(1.0, confidence)

    return GroundingResult(
        dist        = dist,
        cos_th      = math.cos(yaw_err),
        sin_th      = math.sin(yaw_err),
        confidence  = confidence,
        not_visible = False,
        mask        = blob_mask if return_mask else None,
        bbox        = (x, y, w, h),
    )


# ---------------------------------------------------------------------------
# Validation against dataset GT
# ---------------------------------------------------------------------------
def validate_grounding(
    dataset_dir: str,
    n_frames:    int  = 500,
    verbose:     bool = True,
) -> dict:
    """
    Compare grounding output against privileged GT goal from a generated dataset.

    Parameters
    ----------
    dataset_dir : path produced by gen_dataset.py
    n_frames    : number of frames to sample for validation
    verbose     : print per-episode summary

    Returns
    -------
    dict: mean_dist_err, mean_bearing_err_deg, detection_rate, n_eval
    """
    import glob
    import json

    data_dir  = os.path.join(dataset_dir, "data", "chunk-000")
    meta_dir  = os.path.join(dataset_dir, "meta")
    video_dir = os.path.join(dataset_dir, "videos")

    parquet_files = sorted(glob.glob(os.path.join(data_dir, "episode_*.parquet")))
    if not parquet_files:
        raise FileNotFoundError(f"No parquet files found in {data_dir}")

    # Read tasks
    tasks = {}
    try:
        tasks_path = os.path.join(meta_dir, "tasks.jsonl")
        with open(tasks_path) as f:
            for line in f:
                t = json.loads(line)
                tasks[t["task_index"]] = t["task"]
    except Exception:
        pass

    intr = get_ego_intrinsics(EGO_W, EGO_H, EGO_FOVY)

    dist_errs:    list = []
    bearing_errs: list = []
    n_detected         = 0
    n_total            = 0

    for pf in parquet_files:
        import pandas as pd
        df = pd.read_parquet(pf)
        if df.empty:
            continue

        ep_idx     = int(df["episode_index"].iloc[0])
        task_idx   = int(df["task_index"].iloc[0])
        task_desc  = tasks.get(task_idx, "")

        # Parse colour and shape from instruction
        color, shape = _parse_instruction(task_desc)
        if color is None:
            continue

        # Load ego RGB video
        ego_mp4 = os.path.join(video_dir, f"episode_{ep_idx:06d}_ego.mp4")
        if not os.path.isfile(ego_mp4):
            continue

        # Read frames lazily (one at a time) to avoid MemoryError
        reader = imageio.get_reader(ego_mp4)
        try:
            n_video_frames = reader.count_frames()
        except Exception:
            n_video_frames = len(df)
        reader.close()

        n_ep_frames = min(len(df), n_video_frames)
        n_sample = max(1, n_frames // len(parquet_files))
        n_sample = min(n_sample, n_ep_frames)
        sample_indices = np.linspace(0, n_ep_frames - 1, n_sample, dtype=int)

        reader = imageio.get_reader(ego_mp4)
        for si in sample_indices:
            if si >= len(df) or si >= n_ep_frames:
                continue

            try:
                frame = reader.get_data(int(si))
            except Exception:
                continue

            row      = df.iloc[si]
            gt_goal  = np.array(row["goal"])  # [dist, cosθ, sinθ]
            gt_dist  = float(gt_goal[0])
            gt_bear  = math.atan2(float(gt_goal[2]), float(gt_goal[1]))

            ego_rgb = np.array(frame, dtype=np.uint8)

            # Use a flat synthetic depth map at GT distance (validation mode)
            ego_depth_synth = np.full((EGO_H, EGO_W), gt_dist, dtype=np.float32)

            result = ground(ego_rgb, ego_depth_synth, color, shape, intr)

            n_total += 1
            if not result.not_visible and result.confidence > MIN_CONFIDENCE:
                n_detected += 1
                dist_err   = abs(result.dist - gt_dist)
                pred_bear  = math.atan2(result.sin_th, result.cos_th)
                bear_err   = abs(math.atan2(
                    math.sin(pred_bear - gt_bear),
                    math.cos(pred_bear - gt_bear)
                ))
                dist_errs.append(dist_err)
                bearing_errs.append(math.degrees(bear_err))
        reader.close()

        if n_total >= n_frames:
            break

    detection_rate     = n_detected / max(1, n_total)
    mean_dist_err      = float(np.mean(dist_errs))    if dist_errs    else float("nan")
    mean_bearing_err   = float(np.mean(bearing_errs)) if bearing_errs else float("nan")

    if verbose:
        print(f"\n[grounding validation]")
        print(f"  frames evaluated : {n_total}")
        print(f"  detected         : {n_detected}  ({detection_rate:.2%})")
        print(f"  mean dist err    : {mean_dist_err:.3f} m")
        print(f"  mean bearing err : {mean_bearing_err:.2f} deg")

    return {
        "mean_dist_err":        mean_dist_err,
        "mean_bearing_err_deg": mean_bearing_err,
        "detection_rate":       detection_rate,
        "n_eval":               n_total,
    }


# ---------------------------------------------------------------------------
# Parse colour/shape from instruction string
# ---------------------------------------------------------------------------
def _parse_instruction(instruction: str) -> tuple[Optional[str], Optional[str]]:
    """Extract the first matching colour and shape from a text instruction.

    Uses whole-word matching to avoid false positives like 'red' matching
    inside 'purple-colored'.
    """
    import re
    from code.arena import COLORS, SHAPES  # noqa: already in path
    text = instruction.lower()
    color = next(
        (c[0] for c in COLORS
         if re.search(r'\b' + c[0] + r'\b', text)),
        None,
    )
    shape = next((s[0] for s in SHAPES if s[0] in text), None)
    return color, shape


# Lazy import for imageio (used only in validate_grounding)
try:
    import imageio.v2 as imageio
except ImportError:
    import imageio


# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    import sys

    print("grounding.py smoke test...")

    # Synthetic test: render a red ball in a blank image and try to detect it
    h, w = EGO_H, EGO_W
    img = np.zeros((h, w, 3), dtype=np.uint8)
    img[:, :] = [30, 30, 30]   # dark background

    # Draw a red circle in upper-right quadrant
    cx_pix, cy_pix = w * 3 // 4, h // 3
    cv2.circle(img, (cx_pix, cy_pix), 35, (220, 40, 40), -1)   # RGB red

    depth = np.full((h, w), 3.0, dtype=np.float32)  # flat at 3m
    intr  = get_ego_intrinsics(w, h, EGO_FOVY)

    r = ground(img, depth, "red", "ball", intr, return_mask=True)
    print(f"  detected={not r.not_visible}  dist={r.dist:.2f}m  "
          f"yaw_err={math.degrees(math.atan2(r.sin_th,r.cos_th)):.1f}°  "
          f"conf={r.confidence:.2f}")

    # Blue cube — should not detect (no blue in image)
    r2 = ground(img, depth, "blue", "cube", intr)
    print(f"  blue (not present) detected={not r2.not_visible}  (expected False)")

    assert not r.not_visible, "Failed to detect red ball in synthetic image"
    assert r2.not_visible,    "False positive for blue cube"

    print("grounding.py smoke PASS")
    sys.exit(0)
